name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master # check out code
    - run: sudo apt-get update
    - run: sudo apt-get install python-setuptools valac ninja
    - run: sudo pip install meson
    - run: meson build
    - run: ninja -C build
