name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master # check out code
    - run: sudo apt-get update
    - run: sudo apt-get install python3-setuptools valac libvala-dev libgee-0.8-dev libjsonrpc-glib-1.0-dev ninja-build
    - run: sudo pip3 install meson
    - run: meson build
    - run: ninja -C build
