name: vala-daily

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: sudo add-apt-repository ppa:vala-team/daily
    - run: sudo apt-get update
    - run: sudo apt-get install python3-setuptools valac libvala-0.50-dev libgee-0.8-dev libjsonrpc-glib-1.0-dev gobject-introspection libgirepository1.0-dev ninja-build
    - run: sudo pip3 install meson
    - run: meson build
    - run: ninja -C build
    - uses: elementary/actions/vala-lint@master
      with:
        conf: .vala-lint.conf
        fail: false
